M48
; DRILL file KiCad 10.0.1 date 2026-06-16T17:56:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-16T17:56:20+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X80.85Y-95.4
X85.35Y-95.4
T2
X80.375Y-86.4
X86.375Y-80.4
M30
